<!doctype html>
<html lang="">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test Results Report - Practice Selenium level 1</title>

    <link href="reportng.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="meta">
Generated by <a href="http://www.testng.org" target="_blank">TestNG</a> with <a href="https://github.com/testng-team/reportng" target="_blank">ReportNG</a>
at 23:22 ICT on Wednesday 23 October 2024
    <br/><span
    id="systemInfo">Admin@Soren&nbsp;/&nbsp;Java 11.0.17 (Oracle Corporation)&nbsp;/&nbsp;Windows 11 10.0 (amd64)</span>
</div>
<h1>Practice Selenium level 1</h1>

<p>
    <a href="index.html">Suites</a>
        &#183; <a href="output.html">Log Output</a>
</p>

<p>Test duration
    : 26.572s</p>


    <table class="resultsTable">
        <tr>
            <th colspan="3" class="header failed">Failed Tests</th>
        </tr>
            <tr>
                <td class="group" colspan="3">testcases.TestCases</td>
            </tr>
    <tr>
        <td class="method">
                TC001
        </td>
        <td class="duration">
            2.151s
        </td>
        <td class="result">
            <!-- Display the dependencies for skipped test methods -->


            <!-- Show logger output for the test -->

                <a href="javascript:toggleElement('exception-0', 'block')"
                   title="Click to expand/collapse">
                    <b>java.lang.AssertionError: expected [Wellcome h1uv4c9ktg@email2u.shop] but found []</b>
                </a>
                <br/>
                <div class="stackTrace" id="exception-0">
                        org.testng.Assert.fail(Assert.java:111)<br/>
                        org.testng.Assert.failNotEquals(Assert.java:1578)<br/>
                        org.testng.Assert.assertEqualsImpl(Assert.java:150)<br/>
                        org.testng.Assert.assertEquals(Assert.java:132)<br/>
                        org.testng.Assert.assertEquals(Assert.java:656)<br/>
                        org.testng.Assert.assertEquals(Assert.java:666)<br/>
                        testcases.TestCases.TC001(TestCases.java:37)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
                        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
                        java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
                        org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)<br/>
                        org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)<br/>
                        org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)<br/>
                        org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)<br/>
                        org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)<br/>
                        java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)<br/>
                        java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>
                        org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)<br/>
                        java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>
                        java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>
                        java.base/java.lang.Thread.run(Thread.java:834)<br/>
                </div>
        </td>
    </tr>
    <tr>
        <td class="method">
                TC002
        </td>
        <td class="duration">
            1.749s
        </td>
        <td class="result">
            <!-- Display the dependencies for skipped test methods -->

                <i>Method arguments: </i>
                <span class="arguments">
                    dataobjects.User@6e74ebf5, "There was a problem with your login and/or errors exist in your form."
                </span>
                <br/>

            <!-- Show logger output for the test -->

                <a href="javascript:toggleElement('exception-1', 'block')"
                   title="Click to expand/collapse">
                    <b>java.lang.AssertionError: expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]</b>
                </a>
                <br/>
                <div class="stackTrace" id="exception-1">
                        org.testng.Assert.fail(Assert.java:111)<br/>
                        org.testng.Assert.failNotEquals(Assert.java:1578)<br/>
                        org.testng.Assert.assertEqualsImpl(Assert.java:150)<br/>
                        org.testng.Assert.assertEquals(Assert.java:132)<br/>
                        org.testng.Assert.assertEquals(Assert.java:656)<br/>
                        org.testng.Assert.assertEquals(Assert.java:666)<br/>
                        testcases.TestCases.TC002(TestCases.java:64)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>
                        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
                        java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>
                        org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)<br/>
                        org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)<br/>
                        org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)<br/>
                        java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br/>
                        java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br/>
                        java.base/java.lang.Thread.run(Thread.java:834)<br/>
                </div>
        </td>
    </tr>
    </table>


    <table class="resultsTable" width="100%">
        <tr>
            <th colspan="3" class="header passed">Passed Tests</th>
        </tr>
            <tr>
                <td class="group" colspan="3">testcases.TestCases</td>
            </tr>
    <tr>
        <td class="method">
                TC002
        </td>
        <td class="duration">
            1.503s
        </td>
        <td class="result">
            <!-- Display the dependencies for skipped test methods -->

                <i>Method arguments: </i>
                <span class="arguments">
                    dataobjects.User@26d92481, "There was a problem with your login and/or errors exist in your form."
                </span>
                <br/>

            <!-- Show logger output for the test -->

        </td>
    </tr>
    </table>

<script type="text/javascript" src="reportng.js"></script>
</body>
